project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description: "Course Projects for STA 9750 at Baruch College"
  site-url: "https://victorms-4.github.io/STA9750-2026-FALL/"
  navbar:
    background: primary
    search: false

format:
  html:
    theme: flatly
    toc: false

editor:
  mode: source
